### ISSUE TITLE
Error from ic3

### ISSUE THREAD

**Issue by Mprune** [lilicoding/soot-infoflow-android-iccta#16]
Hi, i want to use  ic3 to generate a ICC model by using  the -protobuf option followed by the path to an output directory. 
So i changed runIC3.sh:
just changed this line: java -Xmx8192m -jar ic3-0.1.0-full.jar -apkormanifest $appPath -input $retargetedPath -cp $forceAndroidJar -protobuf M:\bs\tools\retargeted

But it seems doesn't work. When I run RetargetedApp.jar ,  i got the following errors:

M:\bs\tools\soot-infoflow-android-iccta-master\soot-infoflow-android-iccta-master\iccProvider\ic3>java -Xmx8192m -jar RetargetedApp.jar M:\tools\platforms\android-21\android.jar M:\bs\tools\empty.apk M:\bs\tools\retargeted
Soot started on Mon Jan 07 17:22:38 GMT+08:00 2019
Using 'M:\tools\platforms\android-21\android.jar' as android.jar
Warning: exception while processing dex file 'M:\bs\tools\empty.apk'
Exception: org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:151)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:84)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:54)
        at soot.DexClassProvider.classesOfDex(DexClassProvider.java:121)
        at soot.SourceLocator.getClassesUnder(SourceLocator.java:206)
        at soot.Scene.loadNecessaryClasses(Scene.java:1351)
        at soot.Main.run(Main.java:214)
        at soot.Main.main(Main.java:152)
        at RetargetedApp.main(RetargetedApp.java:24)

Any idea Thanks a lot!
@lilicoding

**Comment by Ryuanxue** [comment]
Excuse me, do you use it in Linux or Windows？I use it in Windows, but I find that the launch file of Epicc is .sh so I dontw know how launch it. If you use it in Windows, could you please tell me how to use it. Thank you！

**Comment by JordanSamhi** [comment]
You error means that the program did not recognize a real APK in the file you provided. Is it an actual APK or did you just create and empty file with the .apk extension ?
