### ISSUE TITLE
[Error from Epicc] "java.lang.RuntimeException: Type mask not found for type com.sristc.etage.LoadActivity"

### ISSUE THREAD

**Issue by muntaha14** [lilicoding/soot-infoflow-android-iccta#5]
Hi,

For a real-life application Epicc reported following error:

>  Spark] Pointer Graph simplified in 0.0 seconds.
java.lang.RuntimeException: Type mask not found for type com.sristc.etage.LoadActivity
	at soot.jimple.spark.internal.TypeManager.get(TypeManager.java:103)
	at soot.jimple.spark.sets.HybridPointsToSet.nativeAddAll(HybridPointsToSet.java:60)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:145)
	at soot.jimple.spark.sets.DoublePointsToSet.addAll(DoublePointsToSet.java:61)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:151)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:539)
	at soot.PackManager.runPacksNormally(PackManager.java:443)
	at soot.PackManager.runPacks(PackManager.java:388)
	at soot.jimple.interproc.cc.ConnectedComponents.computeConnectedComponents(ConnectedComponents.java:249)
	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:83)

APK file could not be attached. Its MD5 is 16c84ac187f6f3d54ab44bf0eb0b4e12. It can be downloaded from virustotal.

Thanks,

**Comment by muntaha14** [comment]
Hi Li Li,
Can you please give a rough estimate of new EPICC's release time?

Thanks,

**Comment by lilicoding** [comment]
From now on, please use [IC3](https://github.com/lilicoding/soot-infoflow-android-iccta/wiki/Usage-of-IC3) to replace the experiments.
I will close this issue first, feel free to reopen it if you still encounter the same problem.

**Comment by muntaha14** [comment]
Verified. No errors occurred with IC3.
