### ISSUE TITLE
[Errors from Epicc] 'java.lang.RuntimeException' errors for real-life apps

### ISSUE THREAD

**Issue by muntaha14** [lilicoding/soot-infoflow-android-iccta#6]
I analysed some real-life applications. For 2 applications, Epicc reported errors. Details are given below

1) App MD5 99800eb1cad6e3a8d5c267b8bda81a26
Error:
> Warning: android.view.MenuItem$OnMenuItemClickListener is a phantom class!
java.lang.RuntimeException: IOException with com.j256.ormlite.field.DatabaseField: null
	at soot.coffi.ClassFile.readClass(ClassFile.java:404)
	at soot.coffi.ClassFile.loadClassFile(ClassFile.java:201)
	at soot.coffi.Util.resolveFromClassFile(Util.java:85)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:45)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:229)
	at soot.SootResolver.bringToSignatures(SootResolver.java:252)
	at soot.SootResolver.bringToBodies(SootResolver.java:288)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.forceResolve(Scene.java:1516)
	at soot.jimple.interproc.cc.ConnectedComponents.computeConnectedComponents(ConnectedComponents.java:180)
	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:83)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at soot.coffi.ClassFile.readClass(ClassFile.java:352)
	... 11 more

2) App MD5 95a277d7371860714aa2c43d67b42852
Error:
> [Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
java.lang.RuntimeException: Trying to create interface invoke expression for non-interface type: com.actionbarsherlock.ActionBarSherlock$Implementation Use JVirtualInvokeExpr or JSpecialInvokeExpr instead!
	at soot.jimple.internal.JInterfaceInvokeExpr.<init>(JInterfaceInvokeExpr.java:46)
	at soot.jimple.Jimple.newInterfaceInvokeExpr(Jimple.java:433)
	at soot.coffi.CFG.generateJimple(CFG.java:4507)
	at soot.coffi.CFG.jimplify(CFG.java:1237)
	at soot.coffi.CFG.jimplify(CFG.java:925)
	at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:100)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:324)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:527)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:418)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:84)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:43)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.SceneTransformer.transform(SceneTransformer.java:45)
	at soot.SceneTransformer.transform(SceneTransformer.java:50)
	at soot.jimple.interproc.cc.ConnectedComponents.detectEntryPoints(ConnectedComponents.java:416)
	at soot.jimple.interproc.cc.ConnectedComponents.computeConnectedComponents(ConnectedComponents.java:225)
	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:83)

APK files could not be attached. These can be downloaded from virustotal.

Thanks,

**Comment by lilicoding** [comment]
From now on, please use [IC3](https://github.com/lilicoding/soot-infoflow-android-iccta/wiki/Usage-of-IC3) to replace the experiments.
I will close this issue first, feel free to reopen it if you still encounter the same problem.
