### ISSUE TITLE
Runtime Exception while running Epic

### ISSUE THREAD

**Issue by vitaliiavdiienko** [lilicoding/soot-infoflow-android-iccta#8]
Hi Developers,

i have created a very simple application with a couple of activities and I wanted to test it with your tool. Unfortunately, Epic throws the following exception:

`Directory: testspace/com.interappsms.apk/retargeted/retargeted/com.interappsms
 [*] parsing manifest '/Users/avdiienko/Documents/workspace_android/com.interappsms/bin/com.interappsms.apk'
Manifest components links:
java.lang.RuntimeException: IOException with android.support.v4.app.FragmentTransaction: null
	at soot.coffi.ClassFile.readClass(ClassFile.java:404)
	at soot.coffi.ClassFile.loadClassFile(ClassFile.java:201)
	at soot.coffi.Util.resolveFromClassFile(Util.java:85)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:45)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:229)
	at soot.SootResolver.bringToSignatures(SootResolver.java:252)
	at soot.SootResolver.bringToBodies(SootResolver.java:288)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
	at soot.SootResolver.resolveClass(SootResolver.java:129)
	at soot.Scene.forceResolve(Scene.java:1516)
	at soot.jimple.interproc.cc.ConnectedComponents.computeConnectedComponents(ConnectedComponents.java:180)
	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:83)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at soot.coffi.ClassFile.readClass(ClassFile.java:352)
	... 11 more`

I will send you my APK by email if you need it in order to reproduce the issue.

Thank you in advance.

Best Regards,
Vitalii

**Comment by lilicoding** [comment]
Hi Vitalii, could you send me your app through email so I can test it. I know that now there are lots of problems in Epicc and now we are working on a new version.

**Comment by vitaliiavdiienko** [comment]
Hi Li,

i have sent it to li.li@uni.lu

Thank you in advance.

Best Regards,
Vitalii
