### ISSUE TITLE
`[IccTA] exception: java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (android.content.ServiceConnection in file null)

### ISSUE THREAD

**Issue by vitaliiavdiienko** [lilicoding/soot-infoflow-android-iccta#9]
Hi all,

one more exception....

`[IccTA] exception: java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (android.content.ServiceConnection in file null). Use JInterfaceInvokeExpr instead!
java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (android.content.ServiceConnection in file null). Use JInterfaceInvokeExpr instead!
        at soot.jimple.internal.JVirtualInvokeExpr.<init>(JVirtualInvokeExpr.java:48)
        at soot.jimple.Jimple.newVirtualInvokeExpr(Jimple.java:406)
        at soot.jimple.infoflow.android.iccta.ICCRedirectionCreator.generateRedirectMethodForBindService(ICCRedirectionCreator.java:465)
        at soot.jimple.infoflow.android.iccta.ICCRedirectionCreator.getRedirectMethod(ICCRedirectionCreator.java:152)
        at soot.jimple.infoflow.android.iccta.ICCRedirectionCreator.redirectToDestination(ICCRedirectionCreator.java:67)
        at soot.jimple.infoflow.android.iccta.AndroidIPCManager.process(AndroidIPCManager.java:168)
        at soot.jimple.infoflow.android.iccta.AndroidIPCManager.updateJimpleForICC(AndroidIPCManager.java:144)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:444)
        at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:301)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:522)
        at soot.jimple.infoflow.android.iccta.TestApps.FDHelper.runAnalysis(FDHelper.java:125)
        at soot.jimple.infoflow.android.iccta.TestApps.Test.main(Test.java:124)`

Thanks in advance.

Best Regards,
Vitalii

**Comment by lilicoding** [comment]
This bug has been solved.
